server:
  port: 8080
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/review-portal
    username: root
    password: syed
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: MYSQL
    openInView: false
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false